### ISSUE TITLE
Cover layout needs width and height

### ISSUE THREAD

**Issue by jacobfentress** [guerillalabs/Sasspool#26]
Otherwise it doesn't work for multimedia frames. Make it:

``` css
.cover, %cover {
    bottom: 0;
    height: 100%;
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    width: 100%;
}
```
