### ISSUE TITLE
add horizontal and vertical centering to spacing.scss

### ISSUE THREAD

**Issue by jacobfentress** [guerillalabs/Sasspool#27]
``` css
%horizontal-center       { margin-left: auto; margin-right: auto; }
```
