### ISSUE TITLE
input font-sizing

### ISSUE THREAD

**Issue by jacobfentress** [guerillalabs/Sasspool#30]
Remove item 2 from:

``` css
 // 1. Correct font family not being inherited in all browsers.
// 2. Correct font size not being inherited in all browsers.
// 3. Address margins set differently in Firefox 4+, Safari 5, and Chrome.
button,
input,
select,
textarea {
    font-family: inherit; // 1
    // font-size: 100%; // 2
    margin: 0; //3
}
```

in reset. Conflicts when using text-size variables for select and textareas.
